# Settings.yml
---
conf.py:
  project: TypoScript in 45 Minutes
  copyright: 2008-2013
  version: 6.1
  release: 6.1
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-Typoscript45Minutes
    github_branch: 6-1
  latex_documents:
  - - Index
    - t3ts45.tex
    - TypoScript in 45 Minutes
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...