# Settings.yml
---
conf.py:
  project: TypoScript in 45 Minutes
  copyright: 2008-2015
  version: 6.1
  release: 6.1
  intersphinx_mapping:
    t3install:
    - https://docs.typo3.org/typo3cms/InstallationGuide
    - null
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference
    - null
    t3templating:
    - https://docs.typo3.org/typo3cms/TemplatingTutorial/
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-Typoscript45Minutes
    github_branch: latest
  latex_documents:
  - - Index
    - t3ts45.tex
    - TypoScript in 45 Minutes
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
